[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
callee = "BJYS8QEhSCk4pgtn6oArSEYNScMeTJmrNCVAzsEHaba3"
caller = "esomF1ntZWPDcz2Epcry2z2tSKuzbcBSYye6MnMkHR1"
cpi_returns = "AktkMCE43KeVyex5TvwCwkBqAqhh8wBdcyE5VK4gKei1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
